### PR TITLE
Map refactor

### PR DESCRIPTION
**Pull request by mindlesstux**
Lets bring this thing up the branches/forks!

### CODE REVIEW

**Comment by mindlesstux** [comment]
It would appear that there is a modification to the C code... where did that come from?

**Comment by terribium** [comment]
I made  a change to C code:
Removed 2 unused variables and 1 unused if-statement at aircraftsToJson()-function.

Added comments to not to convert any json-feed to metric (as it was already working that way due bug): https://github.com/bdavenport/dump1090/commit/3000baf184aaab9d5a64292e27c8ae440c5ce542

**Comment by mindlesstux** [comment]
Must have missed that one when it went through.  When I can get to something that uses git that is not my chromebook I'll hand merge the code as github is saying that we made to much of a change.

**Comment by terribium** [comment]
BTW - here is my map (through CloudFlare) http://map.ideat.eu/ It's on only when my laptop is on... No raspberry yet ;)

**Comment by terribium** [comment]
@bdavenport 
Had some time to spare so managed to merge mapRefactor to master :) Everything should be now ok to send pull request.

Since I like screenshots:
tutka

**Pull request merged**
